Update workflow-run-postlayout-sim.yml

diff --git a/.github/workflows/workflow-run-postlayout-sim.yml b/.github/workflows/workflow-run-postlayout-sim.yml
--- a/.github/workflows/workflow-run-postlayout-sim.yml
+++ b/.github/workflows/workflow-run-postlayout-sim.yml
@@ -101,17 +101,20 @@ jobs:
           cat files_to_copy.txt
 
           USERNAME="${{ steps.getpr.outputs.username }}"
-          ssh baker "mkdir -p ~/simulations/$USERNAME"
+          ssh baker "mkdir -p ~/simulations/$USERNAME; rm -rf ~/simulations/$USERNAME/*"
 
           while IFS= read -r file; do
-            echo "Copying $file to baker:~/simulations/$USERNAME/"
-            scp "submissions/$file" baker:~/simulations/$USERNAME/
-            if [ $? -ne 0 ]; then
-              echo "❌ Failed to copy $file"
-              exit 1
+            if [ -f "submissions/$file" ]; then
+              echo "Copying $file to baker:~/simulations/$USERNAME/"
+              scp "submissions/$file" baker:~/simulations/$USERNAME/
+              if [ $? -ne 0 ]; then
+                echo "❌ Failed to copy $file"
+                exit 1
+              fi
+            else
+              echo "⚠️ File submissions/$file not found (possibly deleted), skipping."
             fi
           done < files_to_copy.txt
-
 
       - name: Run simulation and fetch results
         if: steps.check_files.outputs.found == 'true'
