Update workflow-run-postlayout-sim.yml

diff --git a/.github/workflows/workflow-run-postlayout-sim.yml b/.github/workflows/workflow-run-postlayout-sim.yml
--- a/.github/workflows/workflow-run-postlayout-sim.yml
+++ b/.github/workflows/workflow-run-postlayout-sim.yml
@@ -131,13 +131,20 @@ jobs:
 
             ssh baker "cd simulations && python3 run_circuit_simulation.py $USERNAME/$FILE_BASENAME" \
               > sim_stdout.txt 2> sim_stderr.txt
+            RET_CODE=$?
 
             echo "Fetching new output files from Baker..."
             rsync -avz --ignore-existing --update baker:simulations/$USERNAME/ ./output/
 
             echo "Formatting comment..."
             echo "This is an experimental feature. The goal is to run a circuit simulation on the design, and return the results for human verification." > comment.txt
-            echo "✅ Simulation results for \`$FILE_BASENAME\`" >> comment.txt
+
+            if [ $RET_CODE -eq 0 ]; then
+              echo "✅ Simulation results for \`$FILE_BASENAME\`" >> comment.txt
+            else
+              echo "❌ Simulation failed for \`$FILE_BASENAME\` (exit code $RET_CODE)" >> comment.txt
+            fi
+    
             echo "" >> comment.txt
 
             if [ -s sim_stdout.txt ]; then
@@ -208,7 +215,6 @@ jobs:
           echo "" >> comment.txt
           echo "_To re-run this simulation, comment **please resimulate** below._" >> comment.txt
 
-
       - name: Delete previous simulation comment
         if: steps.check_files.outputs.found == 'true'
         run: |
@@ -216,18 +222,20 @@ jobs:
 
           echo "Checking for previous simulation comment on PR #$PR_NUMBER"
           COMMENTS=$(gh pr view "$PR_NUMBER" --comments --json comments -q '.comments[] | {id: .id, body: .body}' | jq -c '.')
-          
-          DELETE_COMMENT_ID=$(echo "$COMMENTS" | jq 'select(.body | contains("✅ Simulation results for")) | .id' | tail -n1)
-          
+
+          DELETE_COMMENT_ID=$(echo "$COMMENTS" | jq -r 'select(.body | contains("✅ Simulation results for")) | .id' | tail -n1)
+
           if [ -n "$DELETE_COMMENT_ID" ]; then
             echo "Deleting previous comment with ID: $DELETE_COMMENT_ID"
             gh api repos/${{ github.repository }}/issues/comments/$DELETE_COMMENT_ID -X DELETE
+            RET_CODE=$?
+            if [ $RET_CODE -ne 0 ]; then
+              echo "Error with gh command"
           else
             echo "No previous simulation comment found."
           fi
         env:
           GH_TOKEN: ${{ secrets.PAT }}
-  
           
       - name: Post simulation results as PR comment
         if: steps.check_files.outputs.found == 'true'
